[package]
name = "baray-rs"
version = "0.3.4"
edition = "2021"

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
cbc = "0.1.2"
rand = "0.8.5"
reqwest = { version = "0.12.7", features = ["json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "1.0.128"
